env:
  global:
  - VOTE_APP=vote
  - RESULT_APP=result
  - WORKER_APP=worker

sudo: required

services:
  - docker

jobs:
  include:
    - stage: VOTE
      script: 
      - cd vote
      - export TAG=latest
      - docker build -t $VOTE_APP:$TAG -f Dockerfile .
      - docker images
      after_success:
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
        docker tag $VOTE_APP:$TAG $VOTE_APP:$TRAVIS_BUILD_NUMBER;
        docker push $VOTE_APP:$TRAVIS_BUILD_NUMBER;
        fi 
      - docker push $VOTE_APP:$TAG
    - stage: RESULT
      script: 
      - cd vote
      - docker build -t result -f Dockerfile .
    - stage: WORKER
      script: 
      - cd worker
      - docker build -t worker -f Dockerfile .
