env:
  global:
  - VOTE_REPO=kurtcrowley/tek-voting-vote
  - RESULT_REPO=kurtcrowley/tek-voting-result
  - WORKER_REPO=kurtcrowley/tek-voting-worker
  - COMMIT=${TRAVIS_COMMIT::8}


sudo: required

services:
  - docker

jobs:
  include:
    - stage: VOTE
      script: 
      - cd vote
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
      - docker tag $REPO:$COMMIT $REPO:$TAG
      - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
      - docker build -f Dockerfile -t $VOTE_REPO:$COMMIT .
      - docker push $VOTE_REPO
    - stage: RESULT
      script: 
      - cd result
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - docker build -f Dockerfile -t $RESULT_REPO:$COMMIT .
      - docker push $RESULT_REPO
    - stage: WORKER
      script: 
      - cd worker
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - docker build -f Dockerfile -t $WORKER_REPO:$COMMIT .
      - docker push $WORKER_REPO
