env:
  global:
  - VOTE_APP=vote
  - RESULT_APP=result
  - WORKER_APP=worker
  - REPO=kurtcrowley/tek-votingapp-containers
  - COMMIT=${TRAVIS_COMMIT::8}


sudo: required

services:
  - docker

jobs:
  include:
    - stage: VOTE
      script: 
      - cd vote
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
      - docker build -f Dockerfile -t $REPO/vote:$COMMIT .
      - docker tag $REPO/vote:$COMMIT $REPO/vote:$TAG
      - docker tag $REPO/vote:$COMMIT $REPO/vote:travis-$TRAVIS_BUILD_NUMBER
      - docker push $REPO/vote
    - stage: RESULT
      script: 
      - cd vote
      - docker build -t result -f Dockerfile .
    - stage: WORKER
      script: 
      - cd worker
      - docker build -t worker -f Dockerfile .
